name: ReleaseCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/pipeline/release.sh ${{secrets.simple-site-1984}} "folder1/myapp.zip" ${{secrets.AKIA2ORCVLWPGWZNOK6E}} ${{secrets.D4vjPoJVgQ81QscLP/DSJGWn1zvCHGx4f4XerTb0}} "myapp.zip"
